-include ../share/build/Makefile.doc
-include ../../../share/build/Makefile.doc

help:
	@echo "make PDF   -  create AMPS.pdf in the main directory"
	@echo "make clean -  remove temporary files"

PDF: AMPS.pdf

clean:
	rm -f AMPS.aux AMPS.log AMPS.out AMPS.toc
