"""Smoke tests for the three comparison plots generated by run_C10.py."""
from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from run_C10 import make_mlt_plot, make_plot, make_scatter_plot


class PlotSmokeTests(unittest.TestCase):
    """Confirm that C9-style products are written for a small comparison table."""

    def test_all_plot_products_are_created(self) -> None:
        rows = []
        for time_index, timestamp in enumerate((
            "2006-12-14T14:00:00Z",
            "2006-12-15T03:00:00Z",
        )):
            for rigidity_index, rigidity in enumerate((0.174013525, 0.262395866)):
                for hemisphere in ("N", "S"):
                    for mlt in (0.0, 6.0, 12.0, 18.0):
                        observed = 65.0 - time_index - 0.5 * rigidity_index + 0.1 * (mlt / 6.0)
                        modeled = observed + 0.4
                        rows.append({
                            "interval_midpoint_utc": timestamp,
                            "rigidity_gv": rigidity,
                            "hemisphere": hemisphere,
                            "mlt_hour": mlt,
                            "observed_boundary_aacgm_deg": observed,
                            "modeled_boundary_aacgm_deg": modeled,
                            "residual_deg": modeled - observed,
                            "sigma_deg": 0.5,
                        })
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            time_plot = root / "C10_comparison.png"
            scatter_plot = root / "C10_scatter.png"
            mlt_plot = root / "C10_mlt_comparison.png"
            make_plot(rows, time_plot, "GRIDDED")
            make_scatter_plot(rows, scatter_plot, "GRIDDED")
            make_mlt_plot(rows, mlt_plot, "GRIDDED")
            for path in (time_plot, scatter_plot, mlt_plot):
                self.assertTrue(path.exists())
                self.assertGreater(path.stat().st_size, 1000)


if __name__ == "__main__":
    unittest.main()
