#!/usr/bin/env python3
"""C7 — T96/T05 model-to-model vertical-cutoff validation.

C7 compares AMPS with cutoff values generated by independent geomagnetic
backtracing systems.  Two reference sources are supported:

  GEOMAGSPHERE
      T96/T05 vertical-cutoff calculator results.  GeoMagSphere reports lower,
      upper, and an "effective" cutoff defined as the midpoint of the lower and
      upper limits.  C7 therefore compares that reported effective value with
      ``0.5*(Rc_lower+Rc_upper)`` from AMPS, while retaining the AMPS penumbra-
      integral effective cutoff as an additional diagnostic.

  IZMIRAN
      Cutoff2050 exported results.  The input CSV must state whether the reported
      effective cutoff is a lower/upper midpoint or a penumbra integral.  C7 does
      not silently guess this convention.

The authoritative web calculators do not expose a stable bulk API.  This runner
therefore separates reference acquisition from model execution:

  1. ``--prepare-reference-requests`` writes a calculator request manifest.
  2. The user submits/export cases from the external calculator.
  3. ``tools/import_reference.py`` converts exported rows into the strict C7 CSV.
  4. ``run_C7.py --reference FILE`` executes AMPS and evaluates the comparison.

A complete 28-point IZMIRAN T96 reference is bundled with this test, so the
normal validation and run commands do not require ``--reference``. Matplotlib
is optional: when available, the runner writes a compact reference-versus-AMPS
comparison plot in every format named by ``--plot-formats`` (PNG and EPS by
default -- a raster copy for quick viewing and a vector copy suitable for
publication); a missing Matplotlib installation never changes pass/fail.

The default fixed locations follow validation.docx: 500-km geodetic altitude,
latitudes -60,-45,-30,0,30,45,60 degrees and east longitudes 0,90,180,270
degrees.  IZMIRAN request files express the equivalent signed longitudes
0,90,180,-90 degrees to satisfy its accepted [-180,180] input range. AMPS
evaluates a 15-by-90-degree shell and the runner extracts only
those 28 locations, avoiding any ambiguity in geographic-to-GSM conversion.
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import math
import re
import shutil
import statistics
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

TEST_ID = "C7"
EARTH_RADIUS_KM = 6371.2
PROTON_MASS_AMU = 1.007276466621
AMU_KG = 1.66053906660e-27
C_LIGHT_M_S = 299792458.0
MEV_J = 1.0e6 * 1.602176634e-19
MODELS = ("T96", "T05")
SOURCES = ("GEOMAGSPHERE", "IZMIRAN")
SUPPORTED_REFERENCE_PAIRS = {
    ("GEOMAGSPHERE", "T96"),
    ("GEOMAGSPHERE", "T05"),
    ("IZMIRAN", "T96"),
}
SOLVERS = ("GRIDLESS", "GRIDDED", "BOTH")
TARGET_LATS = (-60.0, -45.0, -30.0, 0.0, 30.0, 45.0, 60.0)
TARGET_LONS = (0.0, 90.0, 180.0, 270.0)
MOVER_NAMES = ("BORIS", "HC4", "RK2", "RK4", "RK6", "GC2", "GC4", "GC6", "HYBRID")
BUNDLED_REFERENCE_NAME = "reference_C7_izmiran_t96.csv"


class RawDefaultsHelpFormatter(
    argparse.ArgumentDefaultsHelpFormatter, argparse.RawDescriptionHelpFormatter
):
    """Preserve command examples while still displaying argument defaults."""


# The field order is kept in one place so that template files, imported tables,
# selected-reference snapshots, and comparison outputs remain easy to diff.
# In particular, W1..W6 are flattened into six numeric columns; serializing the
# dataclass tuple directly would create a Python-specific value that cannot be
# read back by the strict reference loader.
REFERENCE_FIELDS = (
    "request_id", "reference_source", "model", "epoch_utc",
    "latitude_deg", "longitude_deg_east", "altitude_km",
    "rc_lower_gv", "rc_upper_gv", "rc_effective_gv",
    "effective_definition", "rigidity_step_gv",
    "dst_nT", "pdyn_nPa", "imf_bx_nT", "imf_by_nT", "imf_bz_nT",
    "sw_vx_kms", "sw_n_cm3",
    "w1", "w2", "w3", "w4", "w5", "w6",
    "reference_version", "citation", "notes",
)


@dataclass(frozen=True)
class ReferenceRow:
    request_id: str
    reference_source: str
    model: str
    epoch_utc: str
    latitude_deg: float
    longitude_deg_east: float
    altitude_km: float
    rc_lower_gv: float
    rc_upper_gv: float
    rc_effective_gv: Optional[float]
    effective_definition: str
    rigidity_step_gv: Optional[float]
    dst_nT: float
    pdyn_nPa: float
    imf_bx_nT: float
    imf_by_nT: float
    imf_bz_nT: float
    sw_vx_kms: float
    sw_n_cm3: float
    w: Tuple[float, float, float, float, float, float]
    reference_version: str
    citation: str
    notes: str


def reference_row_to_dict(row: "ReferenceRow") -> Dict[str, object]:
    """Return one reference row in the portable, strict C7 CSV schema.

    ``dataclasses.asdict`` would emit the six history integrals as a single
    tuple-valued ``w`` field.  The external-reference format deliberately uses
    W1..W6 as independent numeric columns because those values are part of the
    physical T05 state and must remain inspectable and reusable outside Python.
    """

    result: Dict[str, object] = {
        "request_id": row.request_id,
        "reference_source": row.reference_source,
        "model": row.model,
        "epoch_utc": row.epoch_utc,
        "latitude_deg": row.latitude_deg,
        "longitude_deg_east": row.longitude_deg_east,
        "altitude_km": row.altitude_km,
        "rc_lower_gv": row.rc_lower_gv,
        "rc_upper_gv": row.rc_upper_gv,
        "rc_effective_gv": "" if row.rc_effective_gv is None else row.rc_effective_gv,
        "effective_definition": row.effective_definition,
        "rigidity_step_gv": "" if row.rigidity_step_gv is None else row.rigidity_step_gv,
        "dst_nT": row.dst_nT,
        "pdyn_nPa": row.pdyn_nPa,
        "imf_bx_nT": row.imf_bx_nT,
        "imf_by_nT": row.imf_by_nT,
        "imf_bz_nT": row.imf_bz_nT,
        "sw_vx_kms": row.sw_vx_kms,
        "sw_n_cm3": row.sw_n_cm3,
        "reference_version": row.reference_version,
        "citation": row.citation,
        "notes": row.notes,
    }
    for index, value in enumerate(row.w, 1):
        result["w%d" % index] = value
    return {field: result[field] for field in REFERENCE_FIELDS}


@dataclass(frozen=True)
class ModelRow:
    latitude_deg: float
    longitude_deg_east: float
    rc_lower_gv: float
    rc_effective_integral_gv: float
    rc_upper_gv: float
    n_unresolved: int
    lower_bracket_unresolved: int
    upper_bracket_unresolved: int
    lower_below_range: int
    lower_above_range: int
    upper_below_range: int
    upper_above_range: int

    @property
    def rc_effective_midpoint_gv(self) -> float:
        return 0.5 * (self.rc_lower_gv + self.rc_upper_gv)


@dataclass
class Metrics:
    source: str
    model: str
    solver: str
    epoch_utc: str
    n_reference: int
    n_matched: int
    n_valid: int
    n_point_pass: int
    matched_fraction: float
    valid_fraction: float
    point_pass_fraction: float
    lower_rmse_gv: float
    upper_rmse_gv: float
    effective_rmse_gv: Optional[float]
    maximum_primary_rmse_gv: float
    passed: bool


def normalize_lon(value: float) -> float:
    """Normalize signed or unsigned east longitude to the C7 [0,360) convention."""
    value = float(value) % 360.0
    return 0.0 if abs(value) < 1.0e-9 or abs(value - 360.0) < 1.0e-9 else value


def signed_lon(value: float) -> float:
    """Return equivalent east longitude in the calculator range [-180,180]."""
    value = normalize_lon(value)
    return value - 360.0 if value > 180.0 else value


def canonical_model(value: str) -> str:
    u = str(value).strip().upper()
    aliases = {"TS96": "T96", "T96S": "T96", "TS05": "T05", "T05S": "T05", "T04S": "T05"}
    u = aliases.get(u, u)
    if u not in MODELS:
        raise ValueError("unsupported model %r; expected T96 or T05" % value)
    return u


def canonical_source(value: str) -> str:
    u = str(value).strip().upper()
    if u not in SOURCES:
        raise ValueError("unsupported reference source %r" % value)
    return u


def optional_float(text: object) -> Optional[float]:
    value = "" if text is None else str(text).strip()
    return None if value == "" else float(value)


def required_float(raw: Mapping[str, str], key: str, path: Path, line: int) -> float:
    value = str(raw.get(key, "")).strip()
    if not value:
        raise RuntimeError("%s:%d missing required numeric field %s" % (path, line, key))
    try:
        result = float(value)
    except ValueError as exc:
        raise RuntimeError("%s:%d invalid %s=%r" % (path, line, key, value)) from exc
    if not math.isfinite(result):
        raise RuntimeError("%s:%d non-finite %s" % (path, line, key))
    return result


def load_references(paths: Sequence[Path]) -> List[ReferenceRow]:
    required = {
        "request_id", "reference_source", "model", "epoch_utc",
        "latitude_deg", "longitude_deg_east", "altitude_km",
        "rc_lower_gv", "rc_upper_gv", "effective_definition",
        "dst_nT", "pdyn_nPa", "imf_bx_nT", "imf_by_nT", "imf_bz_nT",
        "sw_vx_kms", "sw_n_cm3", "w1", "w2", "w3", "w4", "w5", "w6",
    }
    result: List[ReferenceRow] = []
    seen = set()
    for path in paths:
        with path.open(newline="") as stream:
            reader = csv.DictReader(stream)
            missing = sorted(required - set(reader.fieldnames or []))
            if missing:
                raise RuntimeError("%s missing columns: %s" % (path, ", ".join(missing)))
            for line, raw in enumerate(reader, 2):
                source = canonical_source(raw["reference_source"])
                model = canonical_model(raw["model"])
                if (source, model) not in SUPPORTED_REFERENCE_PAIRS:
                    raise RuntimeError(
                        "%s:%d unsupported C7 source/model pair %s/%s; "
                        "GeoMagSphere supplies T96 and T05, while IZMIRAN is "
                        "used only as the secondary T96 check"
                        % (path, line, source, model)
                    )
                definition = str(raw.get("effective_definition", "")).strip().upper()
                if definition not in {"MIDPOINT", "PENUMBRA_INTEGRAL", "REPORTED_UNKNOWN", "NONE"}:
                    raise RuntimeError("%s:%d invalid effective_definition=%r" % (path, line, definition))
                row = ReferenceRow(
                    request_id=str(raw["request_id"]).strip(),
                    reference_source=source,
                    model=model,
                    epoch_utc=str(raw["epoch_utc"]).strip(),
                    latitude_deg=required_float(raw, "latitude_deg", path, line),
                    longitude_deg_east=normalize_lon(required_float(raw, "longitude_deg_east", path, line)),
                    altitude_km=required_float(raw, "altitude_km", path, line),
                    rc_lower_gv=required_float(raw, "rc_lower_gv", path, line),
                    rc_upper_gv=required_float(raw, "rc_upper_gv", path, line),
                    rc_effective_gv=optional_float(raw.get("rc_effective_gv")),
                    effective_definition=definition,
                    rigidity_step_gv=optional_float(raw.get("rigidity_step_gv")),
                    dst_nT=required_float(raw, "dst_nT", path, line),
                    pdyn_nPa=required_float(raw, "pdyn_nPa", path, line),
                    imf_bx_nT=required_float(raw, "imf_bx_nT", path, line),
                    imf_by_nT=required_float(raw, "imf_by_nT", path, line),
                    imf_bz_nT=required_float(raw, "imf_bz_nT", path, line),
                    sw_vx_kms=required_float(raw, "sw_vx_kms", path, line),
                    sw_n_cm3=required_float(raw, "sw_n_cm3", path, line),
                    w=tuple(required_float(raw, "w%d" % i, path, line) for i in range(1, 7)),
                    reference_version=str(raw.get("reference_version", "")).strip(),
                    citation=str(raw.get("citation", "")).strip(),
                    notes=str(raw.get("notes", "")).strip(),
                )
                if row.rc_upper_gv < row.rc_lower_gv:
                    raise RuntimeError("%s:%d upper cutoff is below lower cutoff" % (path, line))
                if source == "GEOMAGSPHERE":
                    # GeoMagSphere's public calculator documentation defines the
                    # reported effective cutoff as the midpoint of its lower and
                    # upper cutoffs.  Requiring that declaration here prevents a
                    # superficially good comparison between unlike quantities.
                    if definition != "MIDPOINT":
                        raise RuntimeError("%s:%d GeoMagSphere rows must declare MIDPOINT" % (path, line))
                    if row.rc_effective_gv is None:
                        raise RuntimeError("%s:%d GeoMagSphere row is missing rc_effective_gv" % (path, line))
                    midpoint = 0.5 * (row.rc_lower_gv + row.rc_upper_gv)
                    tolerance = max(0.051, 0.6 * (row.rigidity_step_gv or 0.1))
                    if abs(row.rc_effective_gv - midpoint) > tolerance:
                        raise RuntimeError(
                            "%s:%d GeoMagSphere effective cutoff %.6g is inconsistent with "
                            "the documented midpoint %.6g" %
                            (path, line, row.rc_effective_gv, midpoint)
                        )
                key = (source, model, row.epoch_utc, round(row.latitude_deg, 7), round(row.longitude_deg_east, 7))
                if key in seen:
                    raise RuntimeError("duplicate C7 reference row: %s" % (key,))
                seen.add(key)
                result.append(row)
    if not result:
        raise RuntimeError("no populated C7 reference rows were loaded")
    return result


def group_key(row: ReferenceRow) -> Tuple[object, ...]:
    return (
        row.reference_source, row.model, row.epoch_utc, row.altitude_km,
        row.dst_nT, row.pdyn_nPa, row.imf_bx_nT, row.imf_by_nT, row.imf_bz_nT,
        row.sw_vx_kms, row.sw_n_cm3, *row.w,
    )


def kinetic_energy_mev(rigidity_gv: float) -> float:
    rest_mev = PROTON_MASS_AMU * AMU_KG * C_LIGHT_M_S ** 2 / MEV_J
    p_mev_c = float(rigidity_gv) * 1000.0
    return math.sqrt(p_mev_c * p_mev_c + rest_mev * rest_mev) - rest_mev


def replace_directive(text: str, directive: str, value: object) -> str:
    lines = text.splitlines()
    output: List[str] = []
    count = 0
    for line in lines:
        stripped = line.lstrip()
        if not stripped or stripped.startswith(("!", "#")):
            output.append(line)
            continue
        tokens = stripped.split(None, 1)
        if tokens[0] != directive:
            output.append(line)
            continue
        count += 1
        comment = ""
        if len(tokens) > 1 and "!" in tokens[1]:
            comment = "  !" + tokens[1].split("!", 1)[1]
        output.append("%-32s%s%s" % (directive, value, comment))
    if count != 1:
        raise RuntimeError("expected one %s directive, found %d" % (directive, count))
    return "\n".join(output) + "\n"


def render_input(template: Path, destination: Path, group: Sequence[ReferenceRow], args: argparse.Namespace, solver: str) -> None:
    first = group[0]
    text = template.read_text()
    values: Dict[str, object] = {
        "CUTOFF_EMIN": "%.15g" % kinetic_energy_mev(args.rigidity_min_gv),
        "CUTOFF_EMAX": "%.15g" % kinetic_energy_mev(args.rigidity_max_gv),
        "CUTOFF_UPPER_SCAN_N": args.cutoff_scan_n,
        "CUTOFF_TRACE_POLICY": args.cutoff_trace_policy,
        "CUTOFF_BACKTRACE_CHARGE": args.backtrace_charge,
        "CUTOFF_TRACE_LIMIT_POLICY": args.trace_limit_policy,
        "CUTOFF_MAX_TRAJ_TIME": "%.12g" % args.max_trace_time,
        "FIELD_MODEL": first.model,
        "EPOCH": first.epoch_utc,
        "DST": "%.12g" % first.dst_nT,
        "PDYN": "%.12g" % first.pdyn_nPa,
        "IMF_BX": "%.12g" % first.imf_bx_nT,
        "IMF_BY": "%.12g" % first.imf_by_nT,
        "IMF_BZ": "%.12g" % first.imf_bz_nT,
        "SW_VX": "%.12g" % first.sw_vx_kms,
        "SW_N": "%.12g" % first.sw_n_cm3,
        **{"T05_W%d" % (i + 1): "%.12g" % first.w[i] for i in range(6)},
        "DOMAIN_X_MIN": "%.12g" % (-args.domain_half_size_re * EARTH_RADIUS_KM),
        "DOMAIN_X_MAX": "%.12g" % ( args.domain_half_size_re * EARTH_RADIUS_KM),
        "DOMAIN_Y_MIN": "%.12g" % (-args.domain_half_size_re * EARTH_RADIUS_KM),
        "DOMAIN_Y_MAX": "%.12g" % ( args.domain_half_size_re * EARTH_RADIUS_KM),
        "DOMAIN_Z_MIN": "%.12g" % (-args.domain_half_size_re * EARTH_RADIUS_KM),
        "DOMAIN_Z_MAX": "%.12g" % ( args.domain_half_size_re * EARTH_RADIUS_KM),
        "R_INNER": "%.12g" % EARTH_RADIUS_KM,
        "SHELL_ALTS_KM": "%.12g" % first.altitude_km,
        "DT_TRACE": "%.12g" % args.dt_trace,
        "ADAPTIVE_DT": args.adaptive_dt,
        "MAX_STEPS": args.max_steps,
        "MAX_TRACE_TIME": "%.12g" % args.max_trace_time,
        "MAX_TRACE_DISTANCE": "%.12g" % args.max_trace_distance,
        "TRAP_DETECTION": args.trap_detection,
    }
    if solver == "GRIDDED":
        values.update({
            "MODE3D_MESH_RES_EARTH_RE": "%.12g" % args.mode3d_mesh_res_earth_re,
            "MODE3D_MESH_RES_BOUNDARY_RE": "%.12g" % args.mode3d_mesh_res_boundary_re,
            "MODE3D_MESH_COARSENING": args.mode3d_mesh_coarsening,
            "MODE3D_MESH_EXPONENT": "%.12g" % args.mode3d_mesh_exponent,
        })
    for key, value in values.items():
        text = replace_directive(text, key, value)
    if re.search(r"__[A-Za-z0-9_]+__|\$\{?[A-Za-z_]", "\n".join(
        line for line in text.splitlines() if line.strip() and not line.lstrip().startswith(("!", "#"))
    )):
        raise RuntimeError("generated C7 input contains an unresolved variable")
    text += "\n! C7_REFERENCE_SOURCE %s\n! C7_REFERENCE_MODEL %s\n" % (first.reference_source, first.model)
    destination.write_text(text)


def parse_tecplot(path: Path) -> List[ModelRow]:
    variables: List[str] = []
    values_list: List[List[float]] = []
    for line in path.read_text().splitlines():
        s = line.strip()
        if not s:
            continue
        if s.upper().startswith("VARIABLES"):
            variables = [v.strip().lower().replace("-", "_").replace(" ", "_") for v in re.findall(r'"([^"]+)"', s)]
        elif not s.upper().startswith(("TITLE", "ZONE")):
            try:
                values_list.append([float(v) for v in s.split()])
            except ValueError:
                pass
    required = {
        "lon_deg", "lat_deg", "rc_lower_gv", "rc_effective_gv", "rc_upper_gv",
        "n_unresolved", "lower_bracket_unresolved", "upper_bracket_unresolved",
    }
    optional_flags = (
        "lower_below_range", "lower_above_range",
        "upper_below_range", "upper_above_range",
    )
    missing = sorted(required - set(variables))
    if missing:
        raise RuntimeError("%s missing columns: %s" % (path, ", ".join(missing)))
    idx = {name: variables.index(name) for name in required}
    optional_idx = {name: variables.index(name) for name in optional_flags if name in variables}

    def flag(values: Sequence[float], name: str) -> int:
        column = optional_idx.get(name)
        return 0 if column is None else int(round(values[column]))

    rows = []
    for values in values_list:
        if len(values) < len(variables):
            continue
        rows.append(ModelRow(
            latitude_deg=values[idx["lat_deg"]],
            longitude_deg_east=normalize_lon(values[idx["lon_deg"]]),
            rc_lower_gv=values[idx["rc_lower_gv"]],
            rc_effective_integral_gv=values[idx["rc_effective_gv"]],
            rc_upper_gv=values[idx["rc_upper_gv"]],
            n_unresolved=int(round(values[idx["n_unresolved"]])),
            lower_bracket_unresolved=int(round(values[idx["lower_bracket_unresolved"]])),
            upper_bracket_unresolved=int(round(values[idx["upper_bracket_unresolved"]])),
            lower_below_range=flag(values, "lower_below_range"),
            lower_above_range=flag(values, "lower_above_range"),
            upper_below_range=flag(values, "upper_below_range"),
            upper_above_range=flag(values, "upper_above_range"),
        ))
    if not rows:
        raise RuntimeError("no numeric rows in %s" % path)
    return rows


def coordinate_key(lat: float, lon: float) -> Tuple[float, float]:
    return round(float(lat), 7), round(normalize_lon(lon), 7)


def rmse(values: Sequence[float]) -> float:
    return math.sqrt(statistics.fmean(v * v for v in values)) if values else math.inf


def compare(group: Sequence[ReferenceRow], model_rows: Sequence[ModelRow], args: argparse.Namespace, solver: str) -> Tuple[List[Dict[str, object]], Metrics]:
    first = group[0]
    model_map = {coordinate_key(row.latitude_deg, row.longitude_deg_east): row for row in model_rows}
    details: List[Dict[str, object]] = []
    lower_errors: List[float] = []
    upper_errors: List[float] = []
    effective_errors: List[float] = []
    n_matched = n_valid = n_pass = 0
    for ref in group:
        model = model_map.get(coordinate_key(ref.latitude_deg, ref.longitude_deg_east))
        if model is None:
            details.append({**asdict(ref), "solver": solver, "matched": False, "valid": False, "passed": False, "failure_reason": "missing_coordinate"})
            continue
        n_matched += 1
        range_flags = (
            model.lower_below_range, model.lower_above_range,
            model.upper_below_range, model.upper_above_range,
        )
        valid = (
            model.n_unresolved == 0 and model.lower_bracket_unresolved == 0
            and model.upper_bracket_unresolved == 0 and not any(range_flags)
            and model.rc_lower_gv >= 0.0 and model.rc_upper_gv >= 0.0
        )
        if valid:
            n_valid += 1
        lower_error = model.rc_lower_gv - ref.rc_lower_gv if valid else math.nan
        upper_error = model.rc_upper_gv - ref.rc_upper_gv if valid else math.nan
        if ref.effective_definition == "MIDPOINT":
            effective_model = model.rc_effective_midpoint_gv
        elif ref.effective_definition == "PENUMBRA_INTEGRAL":
            effective_model = model.rc_effective_integral_gv
        else:
            effective_model = math.nan
        effective_error = (
            effective_model - ref.rc_effective_gv
            if valid and ref.rc_effective_gv is not None and math.isfinite(effective_model)
            else math.nan
        )
        step = ref.rigidity_step_gv or args.reference_step_gv
        base_tolerance = max(args.abs_tol_gv, args.step_tolerance_factor * step)
        lower_tolerance = max(base_tolerance, args.rel_tol * max(ref.rc_lower_gv, args.relative_floor_gv))
        upper_tolerance = max(base_tolerance, args.rel_tol * max(ref.rc_upper_gv, args.relative_floor_gv))
        effective_tolerance = (
            max(base_tolerance, args.rel_tol * max(ref.rc_effective_gv or 0.0, args.relative_floor_gv))
            if ref.rc_effective_gv is not None else math.inf
        )
        point_pass = valid and abs(lower_error) <= lower_tolerance and abs(upper_error) <= upper_tolerance
        if math.isfinite(effective_error):
            point_pass = point_pass and abs(effective_error) <= effective_tolerance
        if valid:
            lower_errors.append(lower_error)
            upper_errors.append(upper_error)
            if math.isfinite(effective_error):
                effective_errors.append(effective_error)
            if point_pass:
                n_pass += 1
        details.append({
            **asdict(ref), "solver": solver, "matched": True, "valid": valid,
            "rc_lower_amps_gv": model.rc_lower_gv,
            "rc_upper_amps_gv": model.rc_upper_gv,
            "rc_effective_integral_amps_gv": model.rc_effective_integral_gv,
            "rc_effective_midpoint_amps_gv": model.rc_effective_midpoint_gv,
            "lower_error_gv": lower_error, "upper_error_gv": upper_error,
            "effective_model_selected_gv": effective_model,
            "effective_error_gv": effective_error,
            "lower_tolerance_gv": lower_tolerance,
            "upper_tolerance_gv": upper_tolerance,
            "effective_tolerance_gv": effective_tolerance,
            "passed": point_pass,
            "n_unresolved": model.n_unresolved,
            "lower_bracket_unresolved": model.lower_bracket_unresolved,
            "upper_bracket_unresolved": model.upper_bracket_unresolved,
            "lower_below_range": model.lower_below_range,
            "lower_above_range": model.lower_above_range,
            "upper_below_range": model.upper_below_range,
            "upper_above_range": model.upper_above_range,
            "failure_reason": (
                "" if point_pass else
                "out_of_scan_range" if any(range_flags) else
                "unresolved" if not valid else
                "outside_tolerance"
            ),
        })
    n_reference = len(group)
    matched_fraction = n_matched / n_reference if n_reference else 0.0
    valid_fraction = n_valid / n_reference if n_reference else 0.0
    point_pass_fraction = n_pass / n_valid if n_valid else 0.0
    lower_rmse = rmse(lower_errors)
    upper_rmse = rmse(upper_errors)
    effective_rmse = rmse(effective_errors) if effective_errors else None
    primary = max(lower_rmse, upper_rmse, effective_rmse or 0.0)
    passed = (
        matched_fraction >= args.required_valid_fraction
        and valid_fraction >= args.required_valid_fraction
        and point_pass_fraction >= args.required_pass_fraction
        and primary <= args.rmse_max_gv
    )
    return details, Metrics(
        source=first.reference_source, model=first.model, solver=solver,
        epoch_utc=first.epoch_utc, n_reference=n_reference, n_matched=n_matched,
        n_valid=n_valid, n_point_pass=n_pass, matched_fraction=matched_fraction,
        valid_fraction=valid_fraction, point_pass_fraction=point_pass_fraction,
        lower_rmse_gv=lower_rmse, upper_rmse_gv=upper_rmse,
        effective_rmse_gv=effective_rmse, maximum_primary_rmse_gv=primary,
        passed=passed,
    )


def write_rows(path: Path, rows: Sequence[Mapping[str, object]]) -> None:
    fields: List[str] = []
    seen = set()
    for row in rows:
        for key in row:
            if key not in seen:
                seen.add(key); fields.append(key)
    with path.open("w", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=fields)
        writer.writeheader(); writer.writerows(rows)


def make_case_plot(
    rows: Sequence[Mapping[str, object]],
    output_base: Path,
    title: str,
    formats: Sequence[str] = ("png", "eps"),
) -> List[Path]:
    """Create the C6-style reference-vs-AMPS and residual diagnostic plot.

    C7 judges lower, upper, and (when defined) effective cutoffs, so all three
    quantities are overlaid in the same two-panel layout used by C6. Plotting
    is deliberately optional and has no effect on the numerical pass/fail
    result.

    ``output_base`` carries no suffix; one sibling file is written per entry
    in ``formats`` (``output_base.with_suffix(".png")``, ``".eps"``, ...) from
    the same figure, so the raster and vector copies never drift apart. The
    return value lists only the files actually written, which is ``[]`` when
    Matplotlib is unavailable, there is no valid data to plot, or every
    requested format failed to save -- callers must not treat an empty result
    as an error.
    """

    valid = [row for row in rows if row.get("valid") is True]
    if not valid or not formats:
        return []

    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:
        return []

    definitions = (
        ("Lower", "rc_lower_gv", "rc_lower_amps_gv", "lower_error_gv", "o"),
        ("Upper", "rc_upper_gv", "rc_upper_amps_gv", "upper_error_gv", "s"),
        (
            "Effective",
            "rc_effective_gv",
            "effective_model_selected_gv",
            "effective_error_gv",
            "^",
        ),
    )

    plotted = []
    all_reference: List[float] = []
    all_model: List[float] = []
    for label, reference_key, model_key, error_key, marker in definitions:
        reference: List[float] = []
        model: List[float] = []
        residual: List[float] = []
        for row in valid:
            try:
                reference_value = float(row[reference_key])
                model_value = float(row[model_key])
                residual_value = float(row[error_key])
            except (KeyError, TypeError, ValueError):
                continue
            if not (
                math.isfinite(reference_value)
                and math.isfinite(model_value)
                and math.isfinite(residual_value)
            ):
                continue
            reference.append(reference_value)
            model.append(model_value)
            residual.append(residual_value)
        if reference:
            plotted.append((label, marker, reference, model, residual))
            all_reference.extend(reference)
            all_model.extend(model)

    if not plotted:
        return []

    figure, axes = plt.subplots(1, 2, figsize=(11, 4.5))
    for label, marker, reference, model, residual in plotted:
        axes[0].scatter(
            reference, model, s=18, alpha=0.7, marker=marker, label=label
        )
        axes[1].scatter(
            reference, residual, s=18, alpha=0.7, marker=marker, label=label
        )

    limit = max(all_reference + all_model + [1.0])
    axes[0].plot([0.0, limit], [0.0, limit], linestyle="--", linewidth=1)
    axes[0].set_xlabel("Reference cutoff [GV]")
    axes[0].set_ylabel("AMPS cutoff [GV]")
    axes[0].set_title("Reference vs AMPS")
    axes[0].grid(True, alpha=0.25)
    axes[0].legend()

    axes[1].axhline(0.0, linestyle="--", linewidth=1)
    axes[1].set_xlabel("Reference cutoff [GV]")
    axes[1].set_ylabel("AMPS - reference [GV]")
    axes[1].set_title("Residual")
    axes[1].grid(True, alpha=0.25)
    axes[1].legend()

    figure.suptitle(title)
    figure.tight_layout()

    # EPS/PS have no alpha channel, so Matplotlib's translucent markers
    # (alpha=0.7 above) fall back to opaque fills on that one format.
    # Matplotlib reports this through its logger rather than warnings.warn,
    # so it is muted here rather than with a warnings filter; it is expected
    # on every EPS write and not a sign anything went wrong.
    ps_logger = logging.getLogger("matplotlib.backends.backend_ps")
    previous_level = ps_logger.level
    written: List[Path] = []
    try:
        ps_logger.setLevel(logging.ERROR)
        for fmt in formats:
            destination = output_base.with_suffix("." + fmt.lower().lstrip("."))
            try:
                figure.savefig(destination, dpi=160)
            except Exception as exc:
                print("C7 plot: failed to write %s: %s" % (destination, exc), file=sys.stderr)
                continue
            written.append(destination)
    finally:
        ps_logger.setLevel(previous_level)

    plt.close(figure)
    return written


def run_process(command: Sequence[str], cwd: Path, log: Path) -> int:
    with log.open("w") as stream:
        stream.write("Command:\n  %s\n\n" % " ".join(command)); stream.flush()
        process = subprocess.Popen(list(command), cwd=str(cwd), stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        assert process.stdout is not None
        for line in process.stdout:
            sys.stdout.write(line); sys.stdout.flush(); stream.write(line); stream.flush()
        return process.wait()


def selected_solvers(value: str) -> Tuple[str, ...]:
    return ("GRIDLESS", "GRIDDED") if value == "BOTH" else (value,)


def resolved_dynamic_chunk(args: argparse.Namespace, solver: str) -> int:
    """Resolve an MPI scheduling chunk for the selected solver.

    Gridless cutoff tracing currently schedules locations on MPI ranks and does
    not use the density-thread pool, so its conservative default is one location
    per scheduler request. Mode3D can process locations using its explicit
    thread pool; there a zero CLI value expands to one location per thread.
    """
    if args.dynamic_chunk > 0:
        return args.dynamic_chunk
    return 1 if solver == "GRIDLESS" else max(1, args.nt)


def command_for(args: argparse.Namespace, amps: Path, solver: str) -> List[str]:
    chunk = resolved_dynamic_chunk(args, solver)
    command = [args.mpirun, "-np", str(args.np), str(amps), "-mode", "gridless" if solver == "GRIDLESS" else "3d", "-i", "AMPS_PARAM_C7.in", "-cutoff-search", "PENUMBRA_SCAN", "-cutoff-upper-scan-n", str(args.cutoff_scan_n), "-cutoff-trace-policy", args.cutoff_trace_policy]
    if args.mover:
        command += ["-mover", args.mover]
    if solver == "GRIDLESS":
        command += [
            "-gridless-mpi-scheduler", args.scheduler,
            "-gridless-mpi-dynamic-chunk", str(chunk),
        ]
    else:
        command += ["-mode3d-field-eval", "MESH", "-mode3d-parallel", "THREADS", "-mode3d-threads", str(args.nt), "-mode3d-mpi-scheduler", args.scheduler, "-mode3d-mpi-dynamic-chunk", str(chunk), "-mode3d-mesh-res-earth-re", str(args.mode3d_mesh_res_earth_re), "-mode3d-mesh-res-boundary-re", str(args.mode3d_mesh_res_boundary_re), "-mode3d-mesh-coarsening", args.mode3d_mesh_coarsening, "-mode3d-mesh-exponent", str(args.mode3d_mesh_exponent)]
        if args.mode3d_parallel_field_init:
            command.append("-mode3d-parallel-field-init")
    return command


def prepare_requests(script_dir: Path, output_dir: Path) -> None:
    """Create a self-contained package for acquiring external C7 references.

    The master manifest is useful for inventory, but four smaller request files
    are easier to work through manually because each calculator/model pair can
    be completed and imported independently.  No website is contacted here; the
    generated files are deterministic instructions and schemas only.
    """

    output_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = script_dir / "reference_C7_request_manifest.csv"
    shutil.copy2(manifest_path, output_dir / "C7_reference_requests.csv")
    shutil.copy2(
        script_dir / "reference_C7_geomagsphere_template.csv",
        output_dir / "reference_C7_geomagsphere_template.csv",
    )
    shutil.copy2(
        script_dir / "reference_C7_izmiran_template.csv",
        output_dir / "reference_C7_izmiran_template.csv",
    )
    shutil.copy2(
        script_dir / "tools" / "import_reference.py",
        output_dir / "import_reference.py",
    )

    with manifest_path.open(newline="") as stream:
        manifest_rows = list(csv.DictReader(stream))
    for source, model in sorted(SUPPORTED_REFERENCE_PAIRS):
        selected = [
            dict(row) for row in manifest_rows
            if row.get("reference_source") == source and row.get("model") == model
        ]
        if source == "IZMIRAN":
            # Cutoff2050 accepts latitude in [-90,90] and longitude in
            # [-180,180]. Keep C7's internal comparison convention unchanged:
            # the strict loader normalizes signed longitude back to [0,360).
            for row in selected:
                latitude = float(row["latitude_deg"])
                longitude = signed_lon(float(row["longitude_deg_east"]))
                if not -90.0 <= latitude <= 90.0:
                    raise RuntimeError("IZMIRAN latitude outside [-90,90]: %g" % latitude)
                if not -180.0 <= longitude <= 180.0:
                    raise RuntimeError("IZMIRAN longitude outside [-180,180]: %g" % longitude)
                row["longitude_deg_east"] = "%g" % longitude
        write_rows(
            output_dir / ("C7_requests_%s_%s.csv" % (source.lower(), model.lower())),
            selected,
        )

    text = """# C7 external-calculator request instructions

The package contains three 28-location batches: GeoMagSphere T96, GeoMagSphere
T05, and IZMIRAN T96. Submit each
row to the selected calculator and preserve the exact model version, epoch,
cutoff values, rigidity step, and any returned allowed/forbidden sequence.

GeoMagSphere accepts location, altitude, UTC time, and email; results are sent
asynchronously. Its reported effective cutoff is the lower/upper midpoint, so
set effective_definition=MIDPOINT in the imported reference CSV.

For IZMIRAN Cutoff2050 use the T96 calculation as a secondary check and
export the numerical result rather than transcribing a plot. Enter the request
coordinates exactly as written: latitude is in [-90,90] degrees and signed east
longitude is in [-180,180] degrees. Thus -90 degrees is the same geographic
meridian as 270 degrees east used internally by C7. For consistency with the
bundled IZMIRAN dataset, use a rigidity range of 0.01-20 GV, a 0.1-GV step,
and a maximum flight time of 20 s. C7 intentionally does not create an IZMIRAN
T05 request. Set effective_definition to PENUMBRA_INTEGRAL or MIDPOINT
according to the exported documentation; use REPORTED_UNKNOWN when the
convention cannot be verified, in which case C7 evaluates lower/upper cutoffs
only.

The external calculator's actual driver state must be copied into the final
reference CSV. Do not claim a controlled T96/T05 comparison when the external
service used time-dependent drivers that differ from the AMPS input. For T05,
this includes W1-W6.

After collecting an exported CSV, run the included import_reference.py utility
and then validate the strict result with:

    python srcEarth/test/C7/run_C7.py \
      --reference reference_C7_<source>_<model>.csv \
      --validate-references
"""
    (output_dir / "README_reference_acquisition.md").write_text(text)


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    invoked_name = Path(sys.argv[0]).name or "run_C7.py"
    example_command = "python3 srcEarth/test/C7/%s" % invoked_name
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=RawDefaultsHelpFormatter,
        epilog=(
            "Examples:\n"
            "  Validate the bundled IZMIRAN reference only:\n"
            "    %s --validate-references\n\n"
            "  Preview the default GRIDLESS calculation:\n"
            "    %s --dry-run -np 4\n\n"
            "  Run the bundled IZMIRAN/T96 GRIDLESS comparison:\n"
            "    %s -np 4\n\n"
            "  Run the Mode3D comparison with parallel field initialization:\n"
            "    %s --solver GRIDDED -mode3d-mesh-coarsening LINEAR "
            "-np 4 -nt 16 --mode3d-parallel-field-init\n\n"
            "  Run both solver paths:\n"
            "    %s --solver BOTH -np 4 -nt 16"
            % ((example_command,) * 5)
        ),
    )
    parser.add_argument("--reference", action="append", default=[], metavar="CSV", help="populated strict C7 reference CSV; repeatable")
    parser.add_argument("--source", choices=("ALL",) + SOURCES, default="IZMIRAN")
    parser.add_argument("--models", default="T96")
    parser.add_argument("--solver", choices=SOLVERS, default="GRIDLESS")
    parser.add_argument("--prepare-reference-requests", action="store_true")
    parser.add_argument("--request-output-dir", default="test_output/C7_reference_requests")
    parser.add_argument("--validate-references", action="store_true")
    parser.add_argument("-np", type=int, default=4)
    parser.add_argument("-nt", type=int, default=16)
    parser.add_argument(
        "--mode3d-parallel-field-init", action="store_true",
        help=("Parallelize Mode3D background magnetic-field initialization with "
              "the existing -nt POSIX-thread count; GRIDDED runs only"),
    )
    parser.add_argument("--amps", default="./amps")
    parser.add_argument("--mpirun", default="mpirun")
    parser.add_argument("--workdir", default="test_output/C7")
    parser.add_argument("--mover", choices=MOVER_NAMES, type=str.upper, default="RK4")
    parser.add_argument("--scheduler", choices=("DYNAMIC", "BLOCK_CYCLIC", "STATIC"), default="DYNAMIC")
    parser.add_argument(
        "--dynamic-chunk", type=int, default=0,
        help=("MPI dynamic-scheduler chunk; 0 selects 1 for GRIDLESS and "
              "the requested Mode3D thread count for GRIDDED")
    )
    parser.add_argument("--rigidity-min-gv", type=float, default=0.01)
    parser.add_argument("--rigidity-max-gv", type=float, default=20.0)
    parser.add_argument("--cutoff-scan-n", type=int, default=400)
    parser.add_argument("--cutoff-trace-policy", choices=("ACCURATE", "LEGACY"), default="ACCURATE")
    parser.add_argument("--backtrace-charge", choices=("REVERSED", "SAME"), default="REVERSED")
    parser.add_argument("--trace-limit-policy", choices=("FORBIDDEN", "UNRESOLVED"), default="FORBIDDEN")
    parser.add_argument("--domain-half-size-re", type=float, default=25.0)
    parser.add_argument("--dt-trace", type=float, default=0.2)
    parser.add_argument("--adaptive-dt", choices=("T", "F"), default="T")
    parser.add_argument("--max-steps", type=int, default=500000)
    parser.add_argument("--max-trace-time", type=float, default=20.0)
    parser.add_argument("--max-trace-distance", type=float, default=400.0)
    parser.add_argument("--trap-detection", choices=("T", "F"), default="T")
    parser.add_argument("--mode3d-mesh-res-earth-re", type=float, default=0.02)
    parser.add_argument("--mode3d-mesh-res-boundary-re", type=float, default=2.0)
    parser.add_argument(
        "-mode3d-mesh-coarsening", "--mode3d-mesh-coarsening",
        dest="mode3d_mesh_coarsening", type=str.upper,
        choices=("LINEAR", "LOG", "EXPONENTIAL", "GEOMETRIC", "POWER", "CONSTANT"),
        default="LOG",
        help=("Mode3D radial AMR mesh-coarsening method; the single-dash form "
              "matches the AMPS executable CLI"),
    )
    parser.add_argument("--mode3d-mesh-exponent", type=float, default=1.0)
    parser.add_argument("--reference-step-gv", type=float, default=0.1)
    parser.add_argument("--step-tolerance-factor", type=float, default=1.5)
    parser.add_argument("--abs-tol-gv", type=float, default=0.20)
    parser.add_argument("--rel-tol", type=float, default=0.10)
    parser.add_argument("--relative-floor-gv", type=float, default=0.5)
    parser.add_argument("--required-valid-fraction", type=float, default=0.95)
    parser.add_argument("--required-pass-fraction", type=float, default=0.85)
    parser.add_argument("--rmse-max-gv", type=float, default=0.50)
    parser.add_argument(
        "--plot-formats", default="png,eps", metavar="FMT[,FMT...]",
        help=("Comma-separated Matplotlib output formats for each case's "
              "C7_comparison plot, e.g. 'png,eps', 'png', or 'png,eps,pdf,svg'; "
              "ignored entirely if Matplotlib is not installed"),
    )
    parser.add_argument("--skip-run", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--keep", action="store_true")
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    if args.np < 1 or args.nt < 1:
        raise SystemExit("-np and -nt must be positive")
    if args.dynamic_chunk < 0:
        raise SystemExit("--dynamic-chunk must be non-negative")
    if args.cutoff_scan_n < 2:
        raise SystemExit("--cutoff-scan-n must be at least 2")
    if not (args.rigidity_max_gv > args.rigidity_min_gv >= 0.0):
        raise SystemExit("require 0 <= rigidity-min-gv < rigidity-max-gv")
    if args.domain_half_size_re <= 1.1:
        raise SystemExit("--domain-half-size-re must exceed the 500-km shell radius")
    supported_plot_formats = {"png", "eps", "pdf", "svg"}
    requested_plot_formats = tuple(dict.fromkeys(
        fmt.strip().lower().lstrip(".") for fmt in args.plot_formats.split(",") if fmt.strip()
    ))
    unsupported_plot_formats = sorted(set(requested_plot_formats) - supported_plot_formats)
    if unsupported_plot_formats:
        raise SystemExit(
            "--plot-formats has unsupported entries: %s (expected any of %s)"
            % (", ".join(unsupported_plot_formats), ", ".join(sorted(supported_plot_formats)))
        )
    args.plot_formats = requested_plot_formats
    script_dir = Path(__file__).resolve().parent
    launch_dir = Path.cwd().resolve()
    if args.prepare_reference_requests:
        output = Path(args.request_output_dir).expanduser()
        if not output.is_absolute(): output = launch_dir / output
        prepare_requests(script_dir, output)
        print("C7 reference request package: %s" % output)
        return 0
    if not args.reference:
        bundled_reference = script_dir / BUNDLED_REFERENCE_NAME
        if not bundled_reference.is_file():
            print(
                "C7 has no --reference argument and the bundled reference is missing: %s"
                % bundled_reference,
                file=sys.stderr,
            )
            return 2
        args.reference = [str(bundled_reference)]
        print("C7 using bundled IZMIRAN reference: %s" % bundled_reference)
    paths = [Path(p).expanduser().resolve() for p in args.reference]
    try:
        references = load_references(paths)
    except Exception as exc:
        print("C7 reference validation failed: %s" % exc, file=sys.stderr)
        return 2
    requested_models = {canonical_model(v) for v in args.models.split(",") if v.strip()}
    references = [r for r in references if r.model in requested_models and (args.source == "ALL" or r.reference_source == args.source)]
    if not references:
        print("No C7 rows remain after --source/--models filtering", file=sys.stderr)
        return 2
    groups: Dict[Tuple[object, ...], List[ReferenceRow]] = {}
    for row in references:
        groups.setdefault(group_key(row), []).append(row)
    for group in groups.values():
        coords = {coordinate_key(r.latitude_deg, r.longitude_deg_east) for r in group}
        expected = {coordinate_key(lat, lon) for lat in TARGET_LATS for lon in TARGET_LONS}
        if coords != expected:
            missing = sorted(expected - coords)
            extra = sorted(coords - expected)
            raise SystemExit("C7 group must contain the planned 28 points; missing=%s extra=%s" % (missing, extra))
    inventory = {"files": [str(p) for p in paths], "rows": len(references), "groups": len(groups), "sources": sorted({r.reference_source for r in references}), "models": sorted({r.model for r in references})}
    if args.validate_references:
        print(json.dumps(inventory, indent=2)); return 0
    work_root = Path(args.workdir).expanduser()
    if not work_root.is_absolute(): work_root = launch_dir / work_root
    if not args.skip_run and not args.keep and work_root.exists(): shutil.rmtree(work_root)
    work_root.mkdir(parents=True, exist_ok=True)
    (work_root / "C7_reference_inventory.json").write_text(json.dumps(inventory, indent=2) + "\n")
    amps = Path(args.amps)
    if not amps.is_absolute(): amps = launch_dir / amps
    all_metrics: List[Metrics] = []
    all_pass = True
    for group_index, group in enumerate(groups.values(), 1):
        first = group[0]
        label = "%s_%s_%s_%02d" % (first.reference_source.lower(), first.model.lower(), re.sub(r"[^0-9]", "", first.epoch_utc)[:12], group_index)
        for solver in selected_solvers(args.solver):
            case_dir = work_root / label / solver.lower()
            case_dir.mkdir(parents=True, exist_ok=True)
            template = script_dir / ("AMPS_PARAM_C7_gridless.in" if solver == "GRIDLESS" else "AMPS_PARAM_C7_mode3d.in")
            render_input(template, case_dir / "AMPS_PARAM_C7.in", group, args, solver)
            write_rows(case_dir / "reference_C7_selected.csv", [reference_row_to_dict(r) for r in group])
            command = command_for(args, amps, solver)
            print("C7 %s/%s command:\n  %s" % (label, solver.lower(), " ".join(command)))
            if not args.skip_run and not args.dry_run:
                rc = run_process(command, case_dir, case_dir / "C7_amps.log")
                if rc != 0: return rc
            if args.dry_run: continue
            output = case_dir / ("cutoff_gridless_shells_penumbra.dat" if solver == "GRIDLESS" else "cutoff_3d_shells_penumbra.dat")
            try:
                model_rows = parse_tecplot(output)
                details, metrics = compare(group, model_rows, args, solver)
            except Exception as exc:
                print("C7 analysis failed for %s/%s: %s" % (label, solver, exc), file=sys.stderr)
                return 2
            write_rows(case_dir / "C7_comparison.csv", details)
            (case_dir / "C7_result.json").write_text(json.dumps(asdict(metrics), indent=2) + "\n")
            plot_paths = make_case_plot(
                details,
                case_dir / "C7_comparison",
                "%s %s %s %s %s" % (
                    TEST_ID,
                    solver,
                    first.reference_source,
                    first.model,
                    first.epoch_utc,
                ),
                args.plot_formats,
            )
            if plot_paths:
                print("C7 %s/%s comparison plot(s): %s" % (
                    label, solver.lower(), ", ".join(p.name for p in plot_paths)
                ))
            all_metrics.append(metrics); all_pass = all_pass and metrics.passed
            print("C7 %s/%s: valid=%d/%d pass_fraction=%.3f lower_RMSE=%.3f upper_RMSE=%.3f max_RMSE=%.3f -> %s" % (label, solver.lower(), metrics.n_valid, metrics.n_reference, metrics.point_pass_fraction, metrics.lower_rmse_gv, metrics.upper_rmse_gv, metrics.maximum_primary_rmse_gv, "PASS" if metrics.passed else "FAIL"))
    (work_root / "C7_summary.json").write_text(json.dumps([asdict(m) for m in all_metrics], indent=2) + "\n")
    if args.dry_run:
        print("C7 dry run complete: %s" % work_root); return 0
    print("C7 overall: %s" % ("PASS" if all_pass else "FAIL"))
    print("Results: %s" % work_root)
    return 0 if all_pass else 1


if __name__ == "__main__":
    raise SystemExit(main())
