#!/usr/bin/env bash
# Adapt the historical standalone BATSRUS check driver to the merged SWMF tree.
# The adapter is used only in the disposable oracle source copy. It never edits
# the pinned checkout and it leaves the top-level SWMF configuration available
# for the multi-instance checks.
set -euo pipefail

SRC=${1:?usage: swmf-batsrus-adapter.sh <swmf-source> <adapted-source>}
DST=${2:?usage: swmf-batsrus-adapter.sh <swmf-source> <adapted-source>}
[ -d "$SRC" ] || { echo "adapter: source is not a directory: $SRC" >&2; exit 2; }
[ ! -e "$DST" ] || { echo "adapter: destination already exists: $DST" >&2; exit 2; }
mkdir -p "$DST"
cp -R "$SRC/." "$DST/"
cd "$DST"

# The source is now code/swmf. Component checks use the GM/BATSRUS copy as the
# code path; the top-level install remains authoritative for share/util and the
# SC/IH/OH/EE slot stubs. Save the generated SWMF files under names that the
# dispatch Makefile can call after a component configuration.
cp Config.pl Config.swmf.pl
if [ -f Makefile ]; then cp Makefile Makefile.swmf.source; fi
if [ -f Makefile.def ]; then cp Makefile.def Makefile.def.swmf.source; fi

# The standalone checks historically called ./Config.pl and `make BATSRUS` from
# the BATSRUS repository root. This wrapper translates only those calls to the
# component directory. A -v/-o/-install=c invocation is a real SWMF operation
# and is delegated unchanged; this is what the ten multi-instance checks use.
cat > Config.pl <<'CONFIG_WRAPPER'
#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd -P)"
args=("$@")
needs_swmf=0
for arg in "${args[@]}"; do
  case "$arg" in
    -v=*|-o=*|-install=c|-install=BATSRUS|-install=s|-amrex|-amrex2d|-amrex3d) needs_swmf=1 ;;
  esac
done
export OPENACC=-noacc
if [ "$needs_swmf" -eq 1 ]; then
  exec "$ROOT/Config.swmf.pl" "${args[@]}"
fi
if [[ " ${args[*]} " == *" -install "* || [[ " ${args[*]} " == *" -install="* ]]; then
  has_noacc=0
  for arg in "${args[@]}"; do [ "$arg" = -noopenacc ] && has_noacc=1; done
  [ "$has_noacc" -eq 1 ] || args+=( -noopenacc )
  "$ROOT/Config.swmf.pl" "${args[@]}"
  # Config.pl -install regenerates the SWMF Makefile. Preserve that genuine
  # file for delegated SWMF targets, then restore the dispatcher for legacy
  # BATSRUS targets in this disposable copy.
  if [ -f "$ROOT/Makefile" ] && ! head -1 "$ROOT/Makefile" | grep -q 'bash'; then
    cp "$ROOT/Makefile" "$ROOT/Makefile.swmf.active"
    cp "$ROOT/.sciaccel_batsrus_makefile.dispatch" "$ROOT/Makefile"
  fi
  exit 0
fi
(
  cd "$ROOT/GM/BATSRUS"
  ./Config.pl "${args[@]}"
)
# Makefile.def is component-specific after -default/-u/-e/-g. Legacy scripts
# resolve it from the old root, so expose that generated file in this private
# adapter copy while retaining the SWMF copy for delegated multi-instance work.
if [ -f "$ROOT/GM/BATSRUS/Makefile.def" ]; then
  cp "$ROOT/GM/BATSRUS/Makefile.def" "$ROOT/Makefile.def"
fi
CONFIG_WRAPPER
chmod +x Config.pl

cat > Makefile <<'MAKE_WRAPPER'
#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd -P)"
# Targets used by the old standalone checks are delegated to GM/BATSRUS. SWMF
# targets are delegated to the top-level makefile generated by Config.swmf.pl.
use_component=0
for arg in "$@"; do
  case "$arg" in
    BATSRUS|PIDL|INTERPOLATE|rundir|rundir_rh|run|parallelrun|serialrun) use_component=1 ;;
  esac
done
if [ "$use_component" -eq 1 ]; then
  exec make -C "$ROOT/GM/BATSRUS" "$@"
fi
if [ -f "$ROOT/Makefile.swmf.active" ]; then
  exec make -f "$ROOT/Makefile.swmf.active" "$@"
fi
if [ -f "$ROOT/Makefile.swmf.source" ]; then
  exec make -f "$ROOT/Makefile.swmf.source" "$@"
fi
exec make -C "$ROOT/GM/BATSRUS" "$@"
MAKE_WRAPPER
chmod +x Makefile

# BATSRUS's standalone rundir recipe expects root-relative Param and Scripts.
# Param is a symlink into the approved component path; Scripts/TEC is copied
# into the existing top-level Scripts directory without changing the source
# checkout's files.
if [ ! -e Param ]; then ln -s GM/BATSRUS/Param Param; fi
mkdir -p Scripts/TEC
if [ -d GM/BATSRUS/Scripts/TEC ]; then cp -R GM/BATSRUS/Scripts/TEC/. Scripts/TEC/; fi

# Once the top-level install runs, preserve its generated Makefile and restore
# this dispatch wrapper. The wrapper's post-install call handles this by
# re-copying the generated file before returning to the check.
cat > .sciaccel_batsrus_restore_makefile.sh <<'RESTORE'
#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd -P)"
if [ -f "$ROOT/Makefile" ] && ! head -1 "$ROOT/Makefile" | grep -q 'bash'; then
  cp "$ROOT/Makefile" "$ROOT/Makefile.swmf.active"
  cp "$ROOT/Makefile.dispatch" "$ROOT/Makefile"
fi
RESTORE
cp Makefile .sciaccel_batsrus_makefile.dispatch
# Config wrapper calls this after top-level install by the check's next command;
# install-time source remains discoverable through Makefile.swmf.active.
# Keep a marker for the run manifest and source-path audit.
printf 'source_root=%s\ncomponent=GM/BATSRUS\nslots=SC/BATSRUS IH/BATSRUS OH/BATSRUS EE/BATSRUS\nopenacc=-noacc\n' "$DST" > .sciaccel-batsrus-adapter
