"""Fail-closed local validator for source-owned Phantom buildbot smokes."""
from __future__ import annotations
import hashlib
import json
import os
import stat
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = "e53ea16758d2a261680506852a528f21270dca1c"
TREE = "ae40f54661feb12f0550092fd2188e5738b7b955"
REQUIRED = ("result.json", "execution.json", "myrun.setup", "myrun.in", "myrun_00000",
            "buildbot.stdout", "buildbot.stderr", "output-manifest.json")


def _sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _json(path):
    try:
        value=json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ValueError("cannot parse %s: %s" % (path.name, exc))
    if not isinstance(value,dict):
        raise ValueError("%s must be an object" % path.name)
    return value


def _manifest(root):
    spec = HERE / "provenance.py"
    import importlib.util
    loader = importlib.util.spec_from_file_location("phantom_hd_provenance", spec)
    module = importlib.util.module_from_spec(loader); loader.loader.exec_module(module)
    path=root/"output-manifest.json"
    declared=_json(path)
    actual=module.records(root, excludes=("output-manifest.json","oracle-manifest.json","active-files-manifest.json","physical-identity.json"))
    if declared.get("schema") != "phantom-output-manifest/v1" or declared.get("files") != actual or declared.get("digest") != module.digest(actual):
        raise ValueError("output manifest is stale or does not cover complete raw output bytes")


def _execution(root, check, result, expected_argv):
    value=_json(root/"execution.json")
    required=("schema","attested","attestation_kind","check","program","argv","exit_code",
              "source_commit","source_tree","executable","input_bytes","raw_evidence","result_sha256")
    if any(key not in value for key in required):
        raise ValueError("execution attestation is incomplete")
    if value["schema"] != "phantom-execution-attestation/v1" or value["attested"] is not True:
        raise ValueError("candidate execution is not attested by the task-local runtime path")
    if value["check"] != check or value["program"] != "scripts/buildbot.sh" or value["exit_code"] != 0:
        raise ValueError("execution attestation command/check/exit mismatch")
    if not isinstance(value["argv"],list) or not value["argv"] or value["argv"][0] != "--parallel":
        raise ValueError("buildbot source-selection argv is missing")
    if value["argv"] != expected_argv:
        raise ValueError("buildbot source-selection argv does not match official catalog")
    if value["source_commit"] != SOURCE or value["source_tree"] != TREE:
        raise ValueError("execution source identity mismatch")
    exe=value["executable"]
    if not isinstance(exe,dict) or not isinstance(exe.get("sha256"),str) or len(exe["sha256"]) != 64:
        raise ValueError("execution executable hash is missing")
    if value["result_sha256"] != _sha(root/"result.json"):
        raise ValueError("execution result hash does not bind result.json bytes")
    if value["input_bytes"] != result["source_generated"]:
        raise ValueError("execution input hashes do not bind source-generated bytes")
    evidence=value["raw_evidence"]
    if not isinstance(evidence,dict) or evidence.get("stdout") != "buildbot.stdout" or evidence.get("stderr") != "buildbot.stderr":
        raise ValueError("execution raw buildbot evidence is incomplete")
    if evidence.get("stdout_sha256") != _sha(root/"buildbot.stdout") or evidence.get("stderr_sha256") != _sha(root/"buildbot.stderr"):
        raise ValueError("execution raw buildbot hashes do not bind stdout/stderr bytes")
    return value


def _catalog(check):
    rows=json.loads((HERE/"checks.json").read_text(encoding="utf-8"))
    matches=[row for row in rows if row.get("id")==check]
    if len(matches)!=1 or matches[0].get("kind")!="buildbot_smoke":
        raise ValueError("buildbot check is not uniquely bound in official catalog")
    return matches[0]


def _one(root, check, row):
    root=Path(root)
    if not root.is_dir() or root.is_symlink(): raise ValueError("row root is missing or a symlink")
    missing=[name for name in REQUIRED if not (root/name).is_file()]
    if missing: raise ValueError("missing buildbot smoke artifact(s): "+", ".join(missing))
    if not (root/"buildbot-logs").is_dir() or (root/"buildbot-logs").is_symlink():
        raise ValueError("raw source buildbot log directory is missing")
    for name in ("myrun.setup","myrun.in","myrun_00000","buildbot.stdout","buildbot.stderr"):
        path=root/name; info=path.lstat()
        if stat.S_ISLNK(info.st_mode) or not stat.S_ISREG(info.st_mode) or info.st_size == 0:
            raise ValueError("source-generated/raw artifact is not a nonempty regular file: "+name)
    result=_json(root/"result.json")
    expected={"schema":"phantom-upstream-buildbot/v1","check":check,"kind":"upstream_registered_procedure","source_commit":SOURCE,"source_tree":TREE,"nfail":0,"return_err":"yes","exit_code":0,"passed":True}
    for key,value in expected.items():
        if result.get(key) != value: raise ValueError("result.json %s mismatch" % key)
    official=row["official_test"]
    expected_argv=[str(value) for value in official["entrypoint"]["argv"]]
    if result.get("setup") != row.get("setup"):
        raise ValueError("result.json setup does not match official catalog")
    if result.get("registration") != official["registration"]["path"]:
        raise ValueError("result.json registration path does not match official catalog")
    if result.get("source_registration_lines") != official["registration"]["lines"]:
        raise ValueError("result.json registration lines do not match official catalog")
    selection=result.get("source_selection")
    expected_selection={"index":int(expected_argv[1]),"nbatch":int(expected_argv[2]),"derivation":"source Makefile_setups non-skipped registration order"}
    if selection != expected_selection:
        raise ValueError("result.json source selection does not match official catalog")
    generated=result.get("source_generated")
    if not isinstance(generated,dict) or set(generated) != {"myrun.setup","myrun.in","myrun_00000"}:
        raise ValueError("result does not identify all source-generated input/dump bytes")
    for name,record in generated.items():
        if record.get("path") != name or record.get("size") != (root/name).stat().st_size or record.get("sha256") != _sha(root/name):
            raise ValueError("source-generated byte hash mismatch for "+name)
    if result.get("raw_logs") != ["buildbot.stdout","buildbot.stderr","buildbot-logs"]:
        raise ValueError("result does not identify raw buildbot logs")
    _execution(root,check,result,expected_argv)
    _manifest(root)
    return result


def validate_check(check, reference_paths, candidate_paths):
    if len(reference_paths)!=1 or len(candidate_paths)!=1:
        return {"check":check,"passed":False,"status":"failed","reason":"exactly one reference and candidate row is required"}
    try:
        row=_catalog(check)
        expected_argv=[str(value) for value in row["official_test"]["entrypoint"]["argv"]]
        a=_one(Path(reference_paths[0]),check,row); b=_one(Path(candidate_paths[0]),check,row)
        for name in ("myrun.setup","myrun.in","myrun_00000"):
            if (Path(reference_paths[0])/name).read_bytes() != (Path(candidate_paths[0])/name).read_bytes():
                raise ValueError("source-generated %s differs between independent runs" % name)
        return {"check":check,"passed":True,"status":"passed","reason":"complete source buildbot setup procedure, generated bytes, raw logs, and nfail=0 provenance validated"}
    except Exception as exc:
        return {"check":check,"passed":False,"status":"failed","reason":str(exc)}


if __name__ == "__main__":
    print(json.dumps(validate_check(sys.argv[1],sys.argv[2:3],sys.argv[3:4]),indent=2,sort_keys=True))
